python3.12.5:
C:\Users\imsve\AppData\Local\Programs\Python\Python312\python.exe

changed C:\intern\xtts-2\server\TTS\utils\synthesizer.py line 252 +255 
changed C:\intern\xtts-2\server\TTS\api.py line 344

C:\Users\imsve\.dstack\server\config.yml

run dstack.yaml with "dstack run run-on-vastai"

{
  "Arabic": "ar",
  "Chinese": "zh-cn",
  "Czech": "cs",
  "Dutch": "nl",
  "English": "en",
  "French": "fr",
  "German": "de",
  "Hungarian": "hu",
  "Italian": "it",
  "Japanese": "ja",
  "Korean": "ko",
  "Polish": "pl",
  "Portuguese": "pt",
  "Russian": "ru",
  "Spanish": "es",
  "Turkish": "tr"
}


в русском проблемы с ударением
voice cloning is okay from english to english, then soso (tested with 25 sec)
убрать пунктуацию в маленьких предложениях и проверить.

